/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    java
}



tasks.named<Jar>("jar"){
    manifest {
        attributes["Main-Class"] = "com.firstApp.Main"
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.grpc:grpc-api:1.73.0")
    implementation("io.grpc:grpc-protobuf:1.71.0")
    // https://mvnrepository.com/artifact/io.grpc/grpc-netty
    implementation("io.grpc:grpc-netty:1.70.0")
    // https://mvnrepository.com/artifact/io.grpc/grpc-stub
    implementation("io.grpc:grpc-stub:1.71.0")
}